openapi: 3.0.0

info:
  title: Expense Tracker API
  description:
    An API for tracking expenses
  contact:
    name: API Support
    email: lib.martinito@pm.me
  version: 1.0.0

servers:
  - url: http://localhost:3000/v1

tags:
  - name: Authentication
    description: Operations related to user authentication and management
  - name: Expenses
    description: Operations related to managing expenses
  - name: User
    description: Operations related to managing users

paths:
  "/register":
    $ref: "./auth/register.yml"
  "/login":
    $ref: "./auth/login.yml"
  "/logout":
    $ref: "./auth/logout.yml"
  "/expenses":
    $ref: "./resources/expenses.yml"
  "/expenses/{expenseId}":
    $ref: "./resources/expense.yml"
  "/users/{userId}":
    $ref: "./resources/user.yml"
