openapi: 3.1.0

info:
  title: Expense Tracker API
  description:
    An API for tracking expenses
  contact:
    name: API Support
    email: lib.martinito@pm.me
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1

tags:
  - name: Authentication
    description: Operations related to user authentication and management

paths:
  "/register":
    post:
      tags:
        - Authentication
      summary: Register a new user
      description: Registers a new account by providing a username, email, password, and password_confirmation.
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
                - username
                - email
                - password
                - password_confirmation
      responses:
        "201":
          description: User successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      type:
                        type: string
                        example: users
                      id:
                        type: integer
                        example: 1
                      attributes:
                        type: object
                        properties:
                          username:
                            type: string
                            example: username
                          email:
                            type: string
                            example: user@example.com
                          created_at:
                            type: string
                            format: date-time
                          updated_at:
                            type: string
                            format: date-time
        "422":
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        status:
                          type: string
                        title:
                          type: string
                        detail:
                          type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        status:
                          type: string
                        title:
                          type: string
                        detail:
                          type: string
  "/login":
    post:
      tags:
        - Authentication
      summary: Login an existing user
      description: Authenticates a user by validating their credentials and returns an access token upon successfull login.
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: User successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      type:
                        type: string
                        example: users
                      id:
                        type: integer
                        example: 1
                      attributes:
                        type: object
                        properties:
                          email:
                            type: string
                            example: user@example.com
                          token:
                            type: string
                            example: tU9bLuZseefXQ4yQxQo8wjtBvsAfPc78os6R
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        status:
                          type: string
                        title:
                          type: string
                        detail:
                          type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        status:
                          type: string
                        title:
                          type: string
                        detail:
                          type: string
  "/logout":
    post:
      tags:
        - Authentication
      summary: Logout the user
      description: Logs out the authenticated user by invalidating their access token.
      operationId: logoutUser
      responses:
        "204":
          description: User successfully logged out
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        status:
                          type: string
                        title:
                          type: string
                        detail:
                          type: string
