openapi: 3.0.0

info:
  title: Expense Tracker API
  description:
    An API for tracking expenses
  contact:
    name: API Support
    email: lib.martinito@pm.me
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1

tags:
  - name: Authentication
    description: Operations related to user authentication and management

paths:
  "/register":
    $ref: "./auth/register.yml"
  "/login":
    $ref: "./auth/login.yml"
  "/logout":
    $ref: "./auth/logout.yml"

components:
  schemas:
    $ref: "./schemas/_index.yml"
  responses:
    $ref: "./responses/_index.yml"
